# Streamlit Secrets Template
# Copy this file to your Streamlit Cloud deployment in the Secrets section
# DO NOT commit the actual secrets.toml file with real API keys to your repository

# API Keys Section
[api_keys]
GOOGLE_API_KEY = "your_google_api_key_here"

# LLM Configuration
LLM_MODEL = "gemini-2.0-pro-exp-02-05"
MAX_TOKENS = "4096"

# Application Settings
DEBUG_MODE = "false"
LOG_LEVEL = "INFO" 
MAX_PDF_SIZE_MB = "10"
MEMORY_TYPE = "conversation_buffer"
MAX_MEMORY_ITEMS = "10"

# Other settings from your .env file
# Add any additional settings your application needs 